#include "strings.h"
#include "arp.h"
#include "hardware/adc_dac.h"
#include "hardware/memory.h"
#include "hardware/midi.h"
#include "hardware/touchstrips.h"
#include "params.h"
#include "sampler.h"
#include "sequencer.h"
#include "synth.h"
#include "time.h"

#define GET_STRING_TOUCH(string_id) (&string_touch[(string_id)][strings_read_frame])
#define CLEAR_STRING(string_id)                                                                                        \
	do {                                                                                                               \
		string_touch[string_id][7].pos = string_touch[string_id][6].pos = string_touch[string_id][5].pos =             \
		    string_touch[string_id][4].pos = string_touch[string_id][3].pos = string_touch[string_id][2].pos =         \
		        string_touch[string_id][1].pos = string_touch[string_id][0].pos = TOUCH_MIN_POS;                       \
		string_touch[string_id][7].pres = string_touch[string_id][6].pres = string_touch[string_id][5].pres =          \
		    string_touch[string_id][4].pres = string_touch[string_id][3].pres = string_touch[string_id][2].pres =      \
		        string_touch[string_id][1].pres = string_touch[string_id][0].pres = TOUCH_MIN_PRES;                    \
	} while (0)

// current frame in string_touch
static u8 strings_write_frame;
static u8 strings_read_frame;

// a string_touch is a virtual touch, it can be generated by a physical touch, latching, arp and sequencer
//
// pointers to this array should always be marked with an s-prefix (s_touch) to differentiate them from pointers named
// "touch", which refer to a physical touch read from the touchstrips
static Touch string_touch[NUM_STRINGS][NUM_TOUCH_FRAMES];
static s16 working_string_pres[NUM_STRINGS];

// the same array as above, but sorted by pitch
static Touch string_touch_sorted[NUM_STRINGS][NUM_TOUCH_FRAMES];

u8 string_touched = 0;
u8 envelope_trigger = 0;

// physical touch mask during the write_frame, used by latch
static u8 phys_string_touch = 0;

typedef struct TouchMemCompressed {
	u8 pos;
	u8 pres;
} TouchMemCompressed;

static TouchMemCompressed latch_touch[NUM_STRINGS];

void clear_latch(void) {
	memset(latch_touch, 0, sizeof(latch_touch));
}

void clear_string(u8 string_id) {
	CLEAR_STRING(string_id);
}

void clear_strings(void) {
	for (u8 string_id = 0; string_id < NUM_STRINGS; string_id++)
		CLEAR_STRING(string_id);
}

u16 get_string_pos(u8 string_id) {
	return GET_STRING_TOUCH(string_id)->pos;
}

const s16* get_string_pressures(void) {
	return &working_string_pres[0];
}

const Touch* sorted_string_touch_ptr(u8 string_id) {
	return &string_touch_sorted[string_id][0];
}

// this combines inputs from touchstrips, latch, arp & sequencer, and saves the resulting Touch in
// string_touch[string_id]
static void generate_string_touch(u8 string_id) {
	static bool suppress_latch = false;
	u8 mask = 1 << string_id;
	bool pres_increasing = false;
	// the touch we're processing
	const Touch* touch = get_touch(string_id, 0);
	// the string-touch that results from that processing
	Touch* s_touch = &string_touch[string_id][strings_write_frame];
	// we save the resulting touch in here until we write it to s_touch
	s16 pressure = TOUCH_MIN_PRES;
	s16 position = TOUCH_MIN_POS;

	// === TOUCH INPUT === //

	// is this string available for the synth?
	if (
	    // default ui, exception for the edit-strip
	    (ui_mode == UI_DEFAULT && !(string_id == 0 && editing_param()))
	    // sampler in preview mode when a sample is loaded
	    || (ui_mode == UI_SAMPLE_EDIT && sampler_mode == SM_PREVIEW && USING_SAMPLER)) {
		bool touching = strip_touched & mask;
		bool first_touch_global = false;

		if (touching) {
			// new touch while nothing was touched
			if (!phys_string_touch)
				first_touch_global = true;
			phys_string_touch |= mask;
			pressure = touch->pres;
			position = touch->pos;
			pres_increasing = pressure > get_touch(string_id, 1)->pres;
		}
		else
			phys_string_touch &= ~mask;

		// === LATCH WRITE === //

		if (latch_active() && touching && pres_increasing) {
			if (first_touch_global) {
				// start a new latch
				clear_latch();

				// in step record mode, trying to start a new latch temporarily turns off latching
				// trying to start a new latch outside of step record mode turns it on again
				suppress_latch = seq_state() == SEQ_STEP_RECORDING;
			}
			// save latch values
			if (!suppress_latch) {
				latch_touch[string_id].pres = pres_compress(pressure);
				latch_touch[string_id].pos = pos_compress(position);
			}
			// RJ: I could not work out a way to work with average values that wasn't
			// sluggish or gave undesired intermediate values - slides and in-between notes
			// Current solution is just saving one value and randomizing when reading it out
			// Result feels great, but good to reconsider when the exact contents of
			// touchstrip and string_touch are more clear

			// Averaging code for reference:
			//
			// u8 max_pos = 0, min_pos = 255, maxpressure = 0;
			// Touch* f = string_touch[string_id];
			// for (int j = 0; j < 8; ++j, ++f) {
			// 	u8 p = clampi((f->pos + 4) / 8, 0, 255);
			// 	min_pos = mini(p, min_pos);
			// 	max_pos = maxi(p, max_pos);
			// 	u8 pr = clampi(f->pres / 12, 0, 255);
			// 	maxpressure = maxi(maxpressure, pr);
			// }
			// latch[string_id].pres = maxpressure;
			// latch[string_id].min_pos = min_pos;
			// latch[string_id].max_pos = max_pos;
		}
	}

	// === LATCH RECALL === //

	// latch pressure larger than touch pressure
	if (latch_active() && latch_touch[string_id].pres > 0 && latch_touch[string_id].pres * 24 > pressure) {
		// recall latch values
		pressure = pres_decompress(latch_touch[string_id].pres);
		position = pos_decompress(latch_touch[string_id].pos);
		pres_increasing = true;

		// Averaging code for reference:
		//
		// int min_pos = latch[string_id].min_pos * 8 + 2;
		// int max_pos = latch[string_id].max_pos * 8 + 6;
		// int avgpos = (min_pos + max_pos) / 2;
		// int range = (max_pos - min_pos) / 4;
		// pressure = latchpres ? rand_range(latchpres - 12, latchpres) : -1024;
		// position = rand_range(avgpos-range,avgpos+range);
	}

	// record touch to sequencer
	seq_try_rec_touch(string_id, pressure, position, pres_increasing);

	// retrieve touch from sequencer
	if (pressure <= 0)
		seq_try_get_touch(string_id, &pressure, &position);

	// === MIDI INPUT === //

	midi_try_get_touch(string_id, &pressure, &position);

	// === CV GATE === //

	// scale pressure with cv gate input
	pressure = pressure * adc_get_smooth(ADC_S_GATE);

	// === FINISHING UP === //

	Touch prev_touch = string_touch[string_id][(strings_write_frame + 7) & 7];

	// no pressure => retain previous frame's position
	if (pressure <= 0)
		position = prev_touch.pos;
	// new finger touch => fill (non-pressed) history with slightly randomized variant of current position
	else if (prev_touch.pres <= 0) {
		Touch* st = string_touch[string_id];
		for (u8 string_id = 0; string_id < NUM_STRINGS; ++string_id, st++)
			if (string_id != strings_write_frame && st->pres <= 0)
				st->pos = position ^ (st->pos & 3);
	}

	// save results to string_touch
	s_touch->pres = pressure;
	s_touch->pos = position;

	// sort string_touch frames by position
	sort8((int*)string_touch_sorted[string_id], (int*)string_touch[string_id]);
}

// manage generating the string_touch array
void generate_string_touches(void) {
	static u8 string_touched_no_arp = 0;
	static u8 string_touched_no_arp_1back = 0;
	static bool do_second_half = false;
	static u8 phys_string_touch_1back = 0;
	static bool prev_latch = false;

	// end latch when necessary
	bool cur_latch = latch_active();
	if (prev_latch && !cur_latch)
		clear_latch();
	prev_latch = cur_latch;

	// update half of the strings (0 - 3 / 4 - 7)
	for (u8 string_id = 0; string_id < NUM_STRINGS / 2; ++string_id)
		generate_string_touch(string_id + do_second_half * NUM_STRINGS / 2);
	// end of a full update of all strings
	if (do_second_half) {
		// lift the last finger in step record mode: auto-step forward
		if (seq_state() == SEQ_STEP_RECORDING && !phys_string_touch && phys_string_touch_1back)
			seq_inc_step();
		phys_string_touch_1back = phys_string_touch;

		// processing the strings happens at a significantly higher framerate than reading out the touchstrips
		// u8 touch_frame tracks which frame in the touches array is currently being written to
		// u8 strings_write_frame tracks which frame in the string_touch array we are writing to
		// we never want any half-filled frames in the string_touch array, so we only update strings_write_frame after
		// processing a full frame of strings

		// in practice, all internal functionality (arp, sequencer, mod sources, etc) get processed at the higher
		// framerate - whenever touchstrips.h has read out a full frame of touches, strings_write_frame increments to
		// make use of the new touch-data

		if (strings_write_frame != touch_frame) {
			// we read from the frame that was written just before
			strings_read_frame = strings_write_frame;
			// we write to the frame that is currently being processed by the touchstrips
			strings_write_frame = touch_frame;
			arp_next_strings_frame_trig();
		}

		// calculate string touches
		string_touched_no_arp_1back = string_touched_no_arp;
		string_touched_no_arp = 0;
		for (u8 string_id = 0; string_id < NUM_STRINGS; ++string_id)
			if (GET_STRING_TOUCH(string_id)->pres > 0)
				string_touched_no_arp |= 1 << string_id;
		envelope_trigger = string_touched_no_arp & ~string_touched_no_arp_1back;

		// new (physical or virtual) touch: restart arp
		if (arp_active() && string_touched_no_arp && !string_touched_no_arp_1back) {
			arp_reset();
			// if the sequencer is not playing, reset the clock so the arp gets a trigger
			if (!seq_playing())
				clock_reset();
		}
	}

	// toggle which half we process
	do_second_half = !do_second_half;

	// generate final touch mask
	string_touched = arp_active() ? arp_tick(string_touched_no_arp) : string_touched_no_arp;

	// precalculate working string pressures
	for (u8 string_id = 0; string_id < NUM_STRINGS; string_id++) {
		working_string_pres[string_id] =
		    (string_touched & (1 << string_id)) ? GET_STRING_TOUCH(string_id)->pres : TOUCH_MIN_PRES;
		if (envelope_trigger & (1 << string_id))
			midi_set_start_velocity(string_id, working_string_pres[string_id]);
	}
}